"""Pure, explainable forecast domain contracts."""

from covenant_radar.domain.forecast.confidence import (
    DEFAULT_CONFIDENCE_FLOOR,
    ConfidenceFactor,
    ConfidenceResult,
    ConfidenceThresholds,
    confidence,
    confidence_value,
)
from covenant_radar.domain.forecast.crossing import (
    CrossingResult,
    ThresholdChange,
    ThresholdPoint,
    crossing,
    crossing_date,
    crossing_for_projection,
    date_crossing,
    find_crossing,
    first_crossing,
)
from covenant_radar.domain.forecast.path import (
    PathPoint,
    Projection,
    build_path,
    project,
    project_path,
    project_with_evidence,
    projection,
)
from covenant_radar.domain.forecast.probability import (
    ProbabilityResult,
    ProbabilityTerm,
    Weights,
    probability,
    probability_value,
)
from covenant_radar.domain.forecast.trend import (
    Direction,
    Observation,
    PressureResult,
    PressureTerm,
    TrendResult,
    compute_pressure,
    evidence_pressure,
    fit,
    fit_trend,
    pressure_from_evidence,
    sum_sustained_pressure,
    trend,
)
from covenant_radar.domain.forecast.predictor import (
    FeatureContribution,
    FeatureSnapshot,
    ForecastPredictor,
    Prediction,
)

__all__ = [
    "CrossingResult",
    "ConfidenceFactor",
    "ConfidenceResult",
    "ConfidenceThresholds",
    "DEFAULT_CONFIDENCE_FLOOR",
    "Direction",
    "FeatureContribution",
    "FeatureSnapshot",
    "ForecastPredictor",
    "Observation",
    "PathPoint",
    "PressureResult",
    "PressureTerm",
    "Prediction",
    "ProbabilityResult",
    "ProbabilityTerm",
    "Projection",
    "TrendResult",
    "Weights",
    "build_path",
    "compute_pressure",
    "confidence",
    "confidence_value",
    "crossing",
    "crossing_date",
    "crossing_for_projection",
    "date_crossing",
    "evidence_pressure",
    "fit",
    "fit_trend",
    "find_crossing",
    "first_crossing",
    "pressure_from_evidence",
    "project",
    "project_path",
    "project_with_evidence",
    "projection",
    "probability",
    "probability_value",
    "sum_sustained_pressure",
    "ThresholdChange",
    "ThresholdPoint",
    "trend",
]
